global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nextjs'
    static_configs:
      - targets: ['host.docker.internal:3000'] 
  - job_name: 'postgres'
    static_configs:
      - targets: ['nyc_pgdb:5432']
